version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: [ "./bin/rails", "server", "-b", "0.0.0.0" ]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: [ "bundle", "exec", "sidekiq" ]

volumes:
  pgdata:
  redisdata:
